# Generated by Django 3.0.3 on 2020-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=255)),
                ('excerpt', models.TextField(default='None', help_text='Post excerpt')),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('body', models.TextField(help_text='Post body')),
                ('published', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True)),
            ],
        ),
    ]
