# Generated by Django 3.0.3 on 2020-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='domain names, zimbabwe, website name, domain, server, vps hosting', help_text='SEO Keywords', max_length=255),
            preserve_default=False,
        ),
    ]
