# Generated by Django 3.0.3 on 2020-03-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(default='None', help_text='Post excerpt', max_length=255),
        ),
    ]
