# Generated by Django 3.0.3 on 2020-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200314_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(default='', help_text='Post excerpt'),
        ),
    ]
