# Generated by Django 3.0.3 on 2020-03-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name', max_length=50)),
                ('status', models.CharField(choices=[('pn', 'Pending'), ('ac', 'Active'), ('ex', 'Expired'), ('tf', 'Transferred')], default='pn', help_text='Status', max_length=50)),
                ('first_name', models.CharField(help_text='Owner first name', max_length=50)),
                ('last_name', models.CharField(help_text='Owner last name', max_length=50)),
                ('business', models.CharField(help_text='Domain business', max_length=100)),
                ('org_name', models.CharField(blank=True, help_text='Organisation name', max_length=50, null=True)),
                ('address', models.TextField(help_text='Physical Address', max_length=200)),
                ('email', models.CharField(help_text='Registrant Email Address', max_length=100)),
                ('phone', models.CharField(help_text='Registrant Phone Number', max_length=50)),
                ('nameserver1', models.CharField(help_text='Nameserver 1', max_length=50)),
                ('nameserver2', models.CharField(help_text='Nameserver 2', max_length=50)),
                ('nameserver3', models.CharField(blank=True, help_text='Nameserver 3', max_length=50, null=True)),
                ('nameserver4', models.CharField(blank=True, help_text='Nameserver 4', max_length=50, null=True)),
                ('nameserver5', models.CharField(blank=True, help_text='Nameserver 5', max_length=50, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'dm_domains',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount')),
                ('phone', models.CharField(help_text='Ecocash phone', max_length=50)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failed')], help_text='Payment status', max_length=50)),
                ('date', models.DateField(auto_now_add=True, help_text='date')),
                ('domain', models.ForeignKey(help_text='Domain name', on_delete=django.db.models.deletion.CASCADE, to='main.Domain')),
            ],
            options={
                'db_table': 'dm_payments',
            },
        ),
    ]
