# Generated by Django 3.0.3 on 2020-03-14 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200314_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 24, 46, 900035, tzinfo=utc)),
        ),
    ]
