# Generated by Django 3.0.3 on 2020-03-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_domain_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount Due')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid')], default='unpaid', help_text='Invoice Status', max_length=20)),
                ('domain', models.ForeignKey(help_text='Domain', on_delete=django.db.models.deletion.CASCADE, to='main.Domain')),
            ],
            options={
                'db_table': 'dm_invoices',
            },
        ),
    ]
