# Generated by Django 3.0.3 on 2020-03-15 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200314_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 8, 30, 25, 61806, tzinfo=utc)),
        ),
    ]
