# Generated by Django 3.0.3 on 2020-03-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200312_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_type', models.CharField(choices=[('int', 'International Domain'), ('loc', 'Local Domains')], help_text='Domain type', max_length=20)),
                ('price', models.FloatField(help_text='Domain price')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main.Domain'),
        ),
    ]
