# Generated by Django 3.0.3 on 2020-03-13 16:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200313_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 16, 33, 22, 200979)),
        ),
        migrations.AddField(
            model_name='domain',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='domain_type',
            field=models.CharField(choices=[('int', 'International Domain'), ('loc', 'Local Domains')], help_text='Domain type', max_length=30),
        ),
    ]
