# Generated by Django 3.0.3 on 2020-03-13 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200313_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 17, 45, 38, 211928)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(help_text='Domain name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 17, 45, 38, 211886)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed')], default='F', help_text='Payment status', max_length=50),
        ),
    ]
