# Generated by Django 3.0.3 on 2020-03-13 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200313_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 17, 47, 6, 713081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 17, 47, 6, 713047, tzinfo=utc)),
        ),
    ]
