# Generated by Django 3.0.3 on 2020-03-14 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200313_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 7, 5, 15, 942539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 7, 5, 15, 942498, tzinfo=utc)),
        ),
    ]
