# Generated by Django 3.0.3 on 2020-03-14 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200314_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 7, 30, 8, 871847, tzinfo=utc)),
        ),
    ]
